# Generated by Django 4.0.6 on 2022-10-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberhouse', '0002_rename_contraseña_usuarios_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='barberhouse/fotos/default.png', upload_to='barberhouse/fotos'),
        ),
    ]
