# Generated by Django 4.0.6 on 2022-10-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberhouse', '0003_usuarios_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='cliente',
            new_name='empleado',
        ),
    ]
