# Generated by Django 4.0.6 on 2022-10-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberhouse', '0004_rename_cliente_citas_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(default='Cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='barberhouse.rol'),
        ),
    ]
